Merge branch 'master' of https://github.com/ACHultman/starter-snake-python JSON quick patch to fix:
 File "/app/app/main.py", line 45, in init
    json_data = json.load(data)
  File "/app/.heroku/python/lib/python2.7/json/__init__.py", line 287, in load
    return loads(fp.read(),
AttributeError: 'dict' object has no attribute 'read'

# Conflicts:
#	app/main.py
#	venv/Include/frameobject.h
#	venv/Include/grammar.h
#	venv/Include/patchlevel.h
#	venv/Include/pgenheaders.h
#	venv/Include/pyconfig.h
#	venv/Include/pyexpat.h
#	venv/LICENSE.txt
#	venv/Lib/locale.py
#	venv/Lib/orig-prefix.txt
#	venv/Lib/posixpath.py
#	venv/Lib/site-packages/bottle-0.12.13.dist-info/RECORD
#	venv/Lib/site-packages/bottle-0.12.13.dist-info/WHEEL
#	venv/Lib/site-packages/gunicorn-19.9.0.dist-info/RECORD
#	venv/Lib/site-packages/pycparser-2.19.dist-info/METADATA
#	venv/Lib/site-packages/pycparser-2.19.dist-info/RECORD
#	venv/Lib/site-packages/pycparser-2.19.dist-info/WHEEL
#	venv/Scripts/activate
#	venv/Scripts/activate.bat
#	venv/Scripts/bottle.py
#	venv/Scripts/easy_install-2.7.exe
#	venv/Scripts/easy_install.exe
#	venv/Scripts/gunicorn.exe
#	venv/Scripts/gunicorn_paster.exe
#	venv/Scripts/pip.exe
#	venv/Scripts/pip2.7.exe
#	venv/Scripts/pip2.exe
#	venv/Scripts/python.exe
#	venv/Scripts/pythonw.exe
#	venv/Scripts/wheel.exe